// Generated by gencpp from file environment/action_srvResponse.msg
// DO NOT EDIT!


#ifndef ENVIRONMENT_MESSAGE_ACTION_SRVRESPONSE_H
#define ENVIRONMENT_MESSAGE_ACTION_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace environment
{
template <class ContainerAllocator>
struct action_srvResponse_
{
  typedef action_srvResponse_<ContainerAllocator> Type;

  action_srvResponse_()
    : complete(0)  {
    }
  action_srvResponse_(const ContainerAllocator& _alloc)
    : complete(0)  {
  (void)_alloc;
    }



   typedef int32_t _complete_type;
  _complete_type complete;




  typedef boost::shared_ptr< ::environment::action_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::environment::action_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct action_srvResponse_

typedef ::environment::action_srvResponse_<std::allocator<void> > action_srvResponse;

typedef boost::shared_ptr< ::environment::action_srvResponse > action_srvResponsePtr;
typedef boost::shared_ptr< ::environment::action_srvResponse const> action_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::environment::action_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::environment::action_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace environment

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'environment': ['/home/utra-art/soccer-rl/ROS_ws/src/environment/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::environment::action_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::environment::action_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::environment::action_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::environment::action_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::environment::action_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::environment::action_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::environment::action_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3608cad0f3f43fe218f81699aeb8ed4";
  }

  static const char* value(const ::environment::action_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3608cad0f3f43feULL;
  static const uint64_t static_value2 = 0x218f81699aeb8ed4ULL;
};

template<class ContainerAllocator>
struct DataType< ::environment::action_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "environment/action_srvResponse";
  }

  static const char* value(const ::environment::action_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::environment::action_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 complete\n\
\n\
";
  }

  static const char* value(const ::environment::action_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::environment::action_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.complete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct action_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::environment::action_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::environment::action_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "complete: ";
    Printer<int32_t>::stream(s, indent + "  ", v.complete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ENVIRONMENT_MESSAGE_ACTION_SRVRESPONSE_H
