// Generated by gencpp from file environment/action_srv.msg
// DO NOT EDIT!


#ifndef ENVIRONMENT_MESSAGE_ACTION_SRV_H
#define ENVIRONMENT_MESSAGE_ACTION_SRV_H

#include <ros/service_traits.h>


#include <environment/action_srvRequest.h>
#include <environment/action_srvResponse.h>


namespace environment
{

struct action_srv
{

typedef action_srvRequest Request;
typedef action_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct action_srv
} // namespace environment


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::environment::action_srv > {
  static const char* value()
  {
    return "b9e4308448306b0b27e98964dd75d3af";
  }

  static const char* value(const ::environment::action_srv&) { return value(); }
};

template<>
struct DataType< ::environment::action_srv > {
  static const char* value()
  {
    return "environment/action_srv";
  }

  static const char* value(const ::environment::action_srv&) { return value(); }
};


// service_traits::MD5Sum< ::environment::action_srvRequest> should match 
// service_traits::MD5Sum< ::environment::action_srv > 
template<>
struct MD5Sum< ::environment::action_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::environment::action_srv >::value();
  }
  static const char* value(const ::environment::action_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::environment::action_srvRequest> should match 
// service_traits::DataType< ::environment::action_srv > 
template<>
struct DataType< ::environment::action_srvRequest>
{
  static const char* value()
  {
    return DataType< ::environment::action_srv >::value();
  }
  static const char* value(const ::environment::action_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::environment::action_srvResponse> should match 
// service_traits::MD5Sum< ::environment::action_srv > 
template<>
struct MD5Sum< ::environment::action_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::environment::action_srv >::value();
  }
  static const char* value(const ::environment::action_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::environment::action_srvResponse> should match 
// service_traits::DataType< ::environment::action_srv > 
template<>
struct DataType< ::environment::action_srvResponse>
{
  static const char* value()
  {
    return DataType< ::environment::action_srv >::value();
  }
  static const char* value(const ::environment::action_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ENVIRONMENT_MESSAGE_ACTION_SRV_H
