// Generated by gencpp from file environment/actor_action_msg.msg
// DO NOT EDIT!


#ifndef ENVIRONMENT_MESSAGE_ACTOR_ACTION_MSG_H
#define ENVIRONMENT_MESSAGE_ACTOR_ACTION_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace environment
{
template <class ContainerAllocator>
struct actor_action_msg_
{
  typedef actor_action_msg_<ContainerAllocator> Type;

  actor_action_msg_()
    : reset(0)
    , action()  {
    }
  actor_action_msg_(const ContainerAllocator& _alloc)
    : reset(0)
    , action(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _reset_type;
  _reset_type reset;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _action_type;
  _action_type action;




  typedef boost::shared_ptr< ::environment::actor_action_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::environment::actor_action_msg_<ContainerAllocator> const> ConstPtr;

}; // struct actor_action_msg_

typedef ::environment::actor_action_msg_<std::allocator<void> > actor_action_msg;

typedef boost::shared_ptr< ::environment::actor_action_msg > actor_action_msgPtr;
typedef boost::shared_ptr< ::environment::actor_action_msg const> actor_action_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::environment::actor_action_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::environment::actor_action_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace environment

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'environment': ['/home/utra-art/soccer-rl/ROS_ws/src/environment/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::environment::actor_action_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::environment::actor_action_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::environment::actor_action_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::environment::actor_action_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::environment::actor_action_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::environment::actor_action_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::environment::actor_action_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f24ef1f066c6c848919ab7da1270cb9";
  }

  static const char* value(const ::environment::actor_action_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f24ef1f066c6c84ULL;
  static const uint64_t static_value2 = 0x8919ab7da1270cb9ULL;
};

template<class ContainerAllocator>
struct DataType< ::environment::actor_action_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "environment/actor_action_msg";
  }

  static const char* value(const ::environment::actor_action_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::environment::actor_action_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 reset\n\
float32[] action\n\
";
  }

  static const char* value(const ::environment::actor_action_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::environment::actor_action_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reset);
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct actor_action_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::environment::actor_action_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::environment::actor_action_msg_<ContainerAllocator>& v)
  {
    s << indent << "reset: ";
    Printer<int32_t>::stream(s, indent + "  ", v.reset);
    s << indent << "action[]" << std::endl;
    for (size_t i = 0; i < v.action.size(); ++i)
    {
      s << indent << "  action[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.action[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ENVIRONMENT_MESSAGE_ACTOR_ACTION_MSG_H
