// Generated by gencpp from file environment/interaction_srv.msg
// DO NOT EDIT!


#ifndef ENVIRONMENT_MESSAGE_INTERACTION_SRV_H
#define ENVIRONMENT_MESSAGE_INTERACTION_SRV_H

#include <ros/service_traits.h>


#include <environment/interaction_srvRequest.h>
#include <environment/interaction_srvResponse.h>


namespace environment
{

struct interaction_srv
{

typedef interaction_srvRequest Request;
typedef interaction_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct interaction_srv
} // namespace environment


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::environment::interaction_srv > {
  static const char* value()
  {
    return "ca1bf07e21318132705d70f9e12ea38c";
  }

  static const char* value(const ::environment::interaction_srv&) { return value(); }
};

template<>
struct DataType< ::environment::interaction_srv > {
  static const char* value()
  {
    return "environment/interaction_srv";
  }

  static const char* value(const ::environment::interaction_srv&) { return value(); }
};


// service_traits::MD5Sum< ::environment::interaction_srvRequest> should match 
// service_traits::MD5Sum< ::environment::interaction_srv > 
template<>
struct MD5Sum< ::environment::interaction_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::environment::interaction_srv >::value();
  }
  static const char* value(const ::environment::interaction_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::environment::interaction_srvRequest> should match 
// service_traits::DataType< ::environment::interaction_srv > 
template<>
struct DataType< ::environment::interaction_srvRequest>
{
  static const char* value()
  {
    return DataType< ::environment::interaction_srv >::value();
  }
  static const char* value(const ::environment::interaction_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::environment::interaction_srvResponse> should match 
// service_traits::MD5Sum< ::environment::interaction_srv > 
template<>
struct MD5Sum< ::environment::interaction_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::environment::interaction_srv >::value();
  }
  static const char* value(const ::environment::interaction_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::environment::interaction_srvResponse> should match 
// service_traits::DataType< ::environment::interaction_srv > 
template<>
struct DataType< ::environment::interaction_srvResponse>
{
  static const char* value()
  {
    return DataType< ::environment::interaction_srv >::value();
  }
  static const char* value(const ::environment::interaction_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ENVIRONMENT_MESSAGE_INTERACTION_SRV_H
