// Generated by gencpp from file environment/interaction_srvResponse.msg
// DO NOT EDIT!


#ifndef ENVIRONMENT_MESSAGE_INTERACTION_SRVRESPONSE_H
#define ENVIRONMENT_MESSAGE_INTERACTION_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <environment/env_observation_msg.h>

namespace environment
{
template <class ContainerAllocator>
struct interaction_srvResponse_
{
  typedef interaction_srvResponse_<ContainerAllocator> Type;

  interaction_srvResponse_()
    : observation()  {
    }
  interaction_srvResponse_(const ContainerAllocator& _alloc)
    : observation(_alloc)  {
  (void)_alloc;
    }



   typedef  ::environment::env_observation_msg_<ContainerAllocator>  _observation_type;
  _observation_type observation;




  typedef boost::shared_ptr< ::environment::interaction_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::environment::interaction_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct interaction_srvResponse_

typedef ::environment::interaction_srvResponse_<std::allocator<void> > interaction_srvResponse;

typedef boost::shared_ptr< ::environment::interaction_srvResponse > interaction_srvResponsePtr;
typedef boost::shared_ptr< ::environment::interaction_srvResponse const> interaction_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::environment::interaction_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::environment::interaction_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace environment

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'environment': ['/home/utra-art/soccer-rl/ROS_ws/src/environment/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::environment::interaction_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::environment::interaction_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::environment::interaction_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::environment::interaction_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::environment::interaction_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::environment::interaction_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::environment::interaction_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "31c1d8987a1485e6848c41d00744b525";
  }

  static const char* value(const ::environment::interaction_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x31c1d8987a1485e6ULL;
  static const uint64_t static_value2 = 0x848c41d00744b525ULL;
};

template<class ContainerAllocator>
struct DataType< ::environment::interaction_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "environment/interaction_srvResponse";
  }

  static const char* value(const ::environment::interaction_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::environment::interaction_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "env_observation_msg observation\n\
\n\
\n\
================================================================================\n\
MSG: environment/env_observation_msg\n\
float32[] state\n\
float32 reward\n\
int32 done\n\
string info\n\
";
  }

  static const char* value(const ::environment::interaction_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::environment::interaction_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.observation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct interaction_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::environment::interaction_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::environment::interaction_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "observation: ";
    s << std::endl;
    Printer< ::environment::env_observation_msg_<ContainerAllocator> >::stream(s, indent + "  ", v.observation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ENVIRONMENT_MESSAGE_INTERACTION_SRVRESPONSE_H
