// Generated by gencpp from file environment/state_srvResponse.msg
// DO NOT EDIT!


#ifndef ENVIRONMENT_MESSAGE_STATE_SRVRESPONSE_H
#define ENVIRONMENT_MESSAGE_STATE_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <environment/env_state_msg.h>

namespace environment
{
template <class ContainerAllocator>
struct state_srvResponse_
{
  typedef state_srvResponse_<ContainerAllocator> Type;

  state_srvResponse_()
    : state()  {
    }
  state_srvResponse_(const ContainerAllocator& _alloc)
    : state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::environment::env_state_msg_<ContainerAllocator>  _state_type;
  _state_type state;




  typedef boost::shared_ptr< ::environment::state_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::environment::state_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct state_srvResponse_

typedef ::environment::state_srvResponse_<std::allocator<void> > state_srvResponse;

typedef boost::shared_ptr< ::environment::state_srvResponse > state_srvResponsePtr;
typedef boost::shared_ptr< ::environment::state_srvResponse const> state_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::environment::state_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::environment::state_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace environment

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'environment': ['/home/utra-art/soccer-rl/ROS_ws/src/environment/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::environment::state_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::environment::state_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::environment::state_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::environment::state_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::environment::state_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::environment::state_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::environment::state_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7972d307c80e773b612efef345e2a97a";
  }

  static const char* value(const ::environment::state_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7972d307c80e773bULL;
  static const uint64_t static_value2 = 0x612efef345e2a97aULL;
};

template<class ContainerAllocator>
struct DataType< ::environment::state_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "environment/state_srvResponse";
  }

  static const char* value(const ::environment::state_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::environment::state_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "env_state_msg state\n\
\n\
\n\
================================================================================\n\
MSG: environment/env_state_msg\n\
float32[] state\n\
int32 done\n\
";
  }

  static const char* value(const ::environment::state_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::environment::state_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct state_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::environment::state_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::environment::state_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    s << std::endl;
    Printer< ::environment::env_state_msg_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ENVIRONMENT_MESSAGE_STATE_SRVRESPONSE_H
