// Generated by gencpp from file environment/state_srv.msg
// DO NOT EDIT!


#ifndef ENVIRONMENT_MESSAGE_STATE_SRV_H
#define ENVIRONMENT_MESSAGE_STATE_SRV_H

#include <ros/service_traits.h>


#include <environment/state_srvRequest.h>
#include <environment/state_srvResponse.h>


namespace environment
{

struct state_srv
{

typedef state_srvRequest Request;
typedef state_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct state_srv
} // namespace environment


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::environment::state_srv > {
  static const char* value()
  {
    return "1c52b5ad9ad4070922180340d7801b38";
  }

  static const char* value(const ::environment::state_srv&) { return value(); }
};

template<>
struct DataType< ::environment::state_srv > {
  static const char* value()
  {
    return "environment/state_srv";
  }

  static const char* value(const ::environment::state_srv&) { return value(); }
};


// service_traits::MD5Sum< ::environment::state_srvRequest> should match 
// service_traits::MD5Sum< ::environment::state_srv > 
template<>
struct MD5Sum< ::environment::state_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::environment::state_srv >::value();
  }
  static const char* value(const ::environment::state_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::environment::state_srvRequest> should match 
// service_traits::DataType< ::environment::state_srv > 
template<>
struct DataType< ::environment::state_srvRequest>
{
  static const char* value()
  {
    return DataType< ::environment::state_srv >::value();
  }
  static const char* value(const ::environment::state_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::environment::state_srvResponse> should match 
// service_traits::MD5Sum< ::environment::state_srv > 
template<>
struct MD5Sum< ::environment::state_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::environment::state_srv >::value();
  }
  static const char* value(const ::environment::state_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::environment::state_srvResponse> should match 
// service_traits::DataType< ::environment::state_srv > 
template<>
struct DataType< ::environment::state_srvResponse>
{
  static const char* value()
  {
    return DataType< ::environment::state_srv >::value();
  }
  static const char* value(const ::environment::state_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ENVIRONMENT_MESSAGE_STATE_SRV_H
