// Generated by gencpp from file environment/state_srvRequest.msg
// DO NOT EDIT!


#ifndef ENVIRONMENT_MESSAGE_STATE_SRVREQUEST_H
#define ENVIRONMENT_MESSAGE_STATE_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace environment
{
template <class ContainerAllocator>
struct state_srvRequest_
{
  typedef state_srvRequest_<ContainerAllocator> Type;

  state_srvRequest_()
    : request_state(0)  {
    }
  state_srvRequest_(const ContainerAllocator& _alloc)
    : request_state(0)  {
  (void)_alloc;
    }



   typedef int32_t _request_state_type;
  _request_state_type request_state;




  typedef boost::shared_ptr< ::environment::state_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::environment::state_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct state_srvRequest_

typedef ::environment::state_srvRequest_<std::allocator<void> > state_srvRequest;

typedef boost::shared_ptr< ::environment::state_srvRequest > state_srvRequestPtr;
typedef boost::shared_ptr< ::environment::state_srvRequest const> state_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::environment::state_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::environment::state_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace environment

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'environment': ['/home/utra-art/soccer-rl/ROS_ws/src/environment/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::environment::state_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::environment::state_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::environment::state_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::environment::state_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::environment::state_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::environment::state_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::environment::state_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "48be3c20da7cd22920845a0d2bc7c79a";
  }

  static const char* value(const ::environment::state_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x48be3c20da7cd229ULL;
  static const uint64_t static_value2 = 0x20845a0d2bc7c79aULL;
};

template<class ContainerAllocator>
struct DataType< ::environment::state_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "environment/state_srvRequest";
  }

  static const char* value(const ::environment::state_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::environment::state_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 request_state\n\
";
  }

  static const char* value(const ::environment::state_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::environment::state_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct state_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::environment::state_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::environment::state_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "request_state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.request_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ENVIRONMENT_MESSAGE_STATE_SRVREQUEST_H
